### ISSUE TITLE
User - Contact a ride owner

### ISSUE THREAD

**Issue by EmCousin** [silvadaniele/covoitsite#10]
# Feature

As a connected user,
I want to be able to contact a ride's owner
to ask them to come aboard their car for the wedding

## Specs
- [x] Add a `first_name`, a `last_name` and a `phone_number` to the table `users`. It is mandatory to fill those fields when you register
- [x] NEVER display an email of a user. Confidentiality ! Hide the email information of the owner on the show page of the ride. Instead, display the full name (first name and last name of the ride owner)
- [x] Add a button "Contact the ride owner" on the show page of the ride.
- [x] When you click on this button, you land on the contact form of the ride owner. This form has two fields : the number of passengers, and the body of the request
- [x] When the user submits the form, it sends an email to the ride owner with : 
  - the fullname of the sender (the user who submitted the form : first_name and last_name)
  - a subject : Example : "#{user.full_name} sent you a request for the ride Paris -> Rennes !"
  - the message of the user
  - A call-to-action button "Answer". When clicking on it, it redirects to the conversation created between the sender and the ride owner

**Comment by silvadaniele** [comment]
Everything good Bro! ;-)

**Comment by EmCousin** [comment]
Awesome job
